name: sgflutterdemo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6
  dio: ^5.0.3
  flutter_screenutil: ^5.7.0
  url_launcher: ^6.1.10
  flutter_easyrefresh: ^2.2.2
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.0
  provider: ^6.0.5
  fluttertoast: ^8.2.1
  fluro: ^2.0.5
  flutter_html: ^2.2.1
  shared_preferences: ^2.0.20
  flutter_daydart: 
    git:
      url: https://github.com/icepy/flutter_daydart
  keyboard_avoider:
    git:
      url: https://github.com/martinrybak/keyboard_avoider

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/src/assets/icon_install1.jpg
    - lib/src/assets/icon_install2.jpg
    - lib/src/assets/icon_install3.jpg
    - lib/src/data/widgets.json
    - lib/src/data/home.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
